markups persistance added
autodesk-platform-services/aps-simple-viewer-nodejs pull request #7
Opened 2023-06-16 14:05 UTC by libvarun

2023-06-19 07:42 UTC, petrbroz requested changes

2023-06-19 07:42 UTC, petrbroz commented on routes/markups.js
> +router.post('/api/markups', bodyParser.json(), async function (req, res, next) {
Express already has a [json body parser](https://www.geeksforgeeks.org/express-js-express-json-function/) built-in. Is there any reason for using the `body-parser` instead?

2023-06-19 07:42 UTC, petrbroz commented on routes/markups.js
> +        const svgString = await fsPromises.readFile(`Markups.svg`, "utf8");
I was a bit surprised to see a single SVG file used for any and every design the user might load in the viewer. What if we simply store one SVG per design URN? It shouldn't make the code more difficult (just replace `/api/markups` with something like `/api/markups/:urn`, and store the files in some temp folder as `temp/<urn>.svg`), and it would be more logical.

2023-06-19 07:42 UTC, petrbroz commented on wwwroot/main.js
> +        const resp = await fetch('/api/markups', { method: 'POST',headers: { "Content-Type": "application/json",}, body: JSON.stringify({ 'data': markupsPdata }) });
I'd suggest to push the markups data as raw SVG in the payload. Or is there any reason to wrap it in a JSON object?

2023-06-19 07:42 UTC, petrbroz commented on wwwroot/main.js
> +        const resp = await fetch('/api/markups', { method: 'GET'});
Consider adding error handling when making fetch calls. Something like `if (!resp.ok) { ... }` should be sufficient.

2023-06-19 07:55 UTC, libvarun commented on routes/markups.js
> +        const svgString = await fsPromises.readFile(`Markups.svg`, "utf8");
this is just POC, the user will have to create and store markup id, urn, and also viewer state in DB.

2023-06-19 07:59 UTC, libvarun commented on wwwroot/main.js
> +        const resp = await fetch('/api/markups', { method: 'POST',headers: { "Content-Type": "application/json",}, body: JSON.stringify({ 'data': markupsPdata }) });
it can be done either way. Not much difference.

2023-06-19 07:59 UTC, libvarun commented on wwwroot/main.js
> +        const resp = await fetch('/api/markups', { method: 'GET'});
ok, will add

2023-06-19 08:00 UTC, libvarun commented on routes/markups.js
> +router.post('/api/markups', bodyParser.json(), async function (req, res, next) {
will replace it and remove the dependency.

2023-06-19 10:22 UTC, libvarun commented
removed body-parser and added error handling.

2023-06-19 12:16 UTC, petrbroz commented on wwwroot/main.js
> +        const resp = await fetch('/api/markups', { method: 'GET'});
I see you're parsing the response JSON **before** checking if the response is actually OK. If the response was not successful for whatever reason, trying to call `await resp.json()` would result in an unexpected error.

2023-06-19 12:20 UTC, petrbroz commented
Thanks @libvarun. As discussed on Slack, let's try and see if we could save/load the markups automatically by setting up handlers for some of the markup events. We could also load the `Autodesk.Viewing.MarkupsGui` extension, and then we wouldn't need any of the custom buttons.

2023-06-22 12:24 UTC, petrbroz commented
Thanks Varun. I'll merge the code but wanted to list a couple more things I noticed in the code that I think should be addressed (some of them to simplify the code, some of them because it's a good practice):

- instead of writing your own code for loading SVG files on the server side, why not just use the `express.static`? For example, like so:
```js
router.get('/api/markups', express.static('data'));
```
That way, when the server receives a request like `/api/markups/some-long-urn.svg`, it will look into the `data` folder for any file called `some-long-urn.svg`, and if there's no such file, the middleware will automatically respond with 404. You could then also include the `data` folder in the `.gitignore` file to make sure that any files stored there are not included in git.

- whenever you're accessing file system based on some value provided by the user (in this case, `urn`), it's a good practice to check or sanitize the input to make sure that the user cannot try something like `../../../passwords`. I know this is just a POC (plus you're appending the `.svg` file extension to the user-provided string) but I believe we should strive for at least some basic level of security even in samples like this.

- when dealing with async functions (or any functions really) that may throw an exception, it's a good practice to handle the exceptions somewhere. In this case the `loadMarkups` and `saveMarkups` functions can potentially throw exceptions, but these would currently be ignored.

2023-06-22 12:25 UTC, merged

2023-06-23 07:37 UTC, libvarun commented
Hi Petr, 
Try Catch blocks are added. about sanitize, it's bit overkill to add sanitize dependency just for 1 value.
We're just providing reusable code snippets, i guess this should be ok?
About static resource, my code is just 2 lines, developer will need similar logic, because they'll be sending additional details like markup id, viewer state, etc..